### Input configuration
#
# Example configuration:
#
#   input "2:14:SynPS/2_Synaptics_TouchPad" {
#       dwt enabled
#       tap enabled
#       natural_scroll enabled
#       middle_emulation enabled
#   }
#
# You can get the names of your inputs by running: swaymsg -t get_inputs
# Read `man 5 sway-input` for more information about this section.

input "1267:12729:ASUE140D:00_04F3:31B9_Touchpad" {
	dwt enabled # disable while typing
	tap enabled
	natural_scroll enabled
}

input * {
    xkb_options compose:rctrl
    xkb_options "caps:swapescape"
}

input type:keyboard {
    xkb_layout "us,be"
}
