# Font

font pango:"JetBrainsMono Nerd Font Propo" 11

# Borders

gaps inner 7
gaps outer 4
gaps top 4

default_border pixel 2
smart_borders yes

set $gnome-schema org.gnome.desktop.interface
exec_always {
    gsettings set $gnome-schema gtk-theme 'Adwaita'
    gsettings set $gnome-schema color-scheme 'prefer-dark'
    gsettings set $gnome-schema cursor-theme 'volantes_cursors'
}
